void pack8(unsigned char *buf, unsigned char val, int *offset);
void pack16(unsigned char *buf, uint16_t val, int *offset);
void pack32(unsigned char *buf, uint32_t val, int *offset);
void pack64(unsigned char *buf, uint64_t val, int *offset);
void packstr(unsigned char *buf, char *str, int *offset);
void packqid(unsigned char *buf, Qid *qid, int *offset);
void packheader(unsigned char *buf, Header *hdr, int *offset);
void unpack8(unsigned char *buf, unsigned char *val, int *offset);
void unpack16(unsigned char *buf, uint16_t *val, int *offset);
void unpack32(unsigned char *buf, uint32_t *val, int *offset);
void unpack64(unsigned char *buf, uint64_t *val, int *offset);
void unpackheader(unsigned char *msg, Header *hdr, int *offset);
void unpackqid(unsigned char *buf, Qid *qid, int *offset);
int unpackstr(unsigned char *buf, uint16_t *len, char *dst, uint32_t size, int *offset);
void unpackstat(unsigned char *buf, Stat *stat, int *offset);
